#!/bin/sh
export GL_USERNAME=""
while read -r OLDREV NEWREV REFNAME; do
  "{{ .Binary }}" analyze \
    --config="{{ .ConfigurationFile }}" \
    --hook-type="pre-receive" \
    --hook-input="$OLDREV $NEWREV $REFNAME" \
    --output-format="{{ .OutputFormat }}"
  status=$?
  if [ $status -eq 1 ]; then
    exit 1
  fi
  exit 0
done
