- conditions:
  - type: pattern
    pattern: (feature|release|hotfix)\/[a-z\d-_.]+
  type: branch
- conditions:
  - type: length
    pattern: lt 120
  - type: pattern
    pattern: (?m)^(?P<type>build|ci|chore|docs|feat|fix|perf|refactor|style|test)(?P<scope>\([a-z]+\))*:\s(?P<subject>[[:word:]\s./'-]+)$
    skip: (?i)(?:initial(?:izing)?)
  - type: email
    pattern: (?m)^[a-zA-Z.\-]+@gmail.com$
    ignore: true
  type: commit
- conditions:
  - skip: .*.go|CONTRIBUTING.md|docs/.*|test/.*
    type: secret
  type: security
- conditions:
  - type: size
    pattern: lt 2mb
  type: file
